package com.example.todolist

object MotivationalQuotes {
    val quotes = listOf(
        "Every dot matters.", "Go out and get it.", "One day closer.", "Make it count.", "Stay consistent.",
        "Small steps, big results.", "Keep the momentum.", "Focus on the win.", "Your future is today.",
        "Push your limits.", "Don't stop now.", "Consistency is key.", "Believe in yourself.", "Work hard, stay humble.",
        "Dream big, do bigger.", "Success is a journey.", "Stay focused.", "Never give up.", "Prove them wrong.",
        "Be your best self.", "One task at a time.", "Own the day.", "Rise and grind.", "Stay hungry.",
        "Chase your dreams.", "Be the change.", "Hard work pays off.", "Keep pushing.", "Stay positive.",
        "Mindset is everything.", "Action is key.", "Start today.", "No excuses.", "Just do it.",
        "Focus on progress.", "Stay disciplined.", "Be productive.", "Master your habits.", "Build your future.",
        "Greatness takes time.", "Keep going.", "You got this.", "Make progress daily.", "Do it for you.",
        "Be legendary.", "Level up.", "Stay sharp.", "Be fearless.", "Seize the day.", "Win the morning.",
        "Stay dedicated.", "Commit to excellence.", "Your only limit is you.", "Turn dreams into reality.",
        "Efficiency is pride.", "Do more, talk less.", "Stay on track.", "Push through.", "Finish strong.",
        "Start where you are.", "Use what you have.", "Do what you can.", "Be unstoppable.", "Keep moving forward.",
        "Small wins add up.", "Celebrate progress.", "Focus on the now.", "Be intentional.", "Life is what you make it.",
        "Create your luck.", "Be persistent.", "Strength in discipline.", "Focus and execute.", "Deliver results.",
        "Be the best.", "Aim high.", "Stay committed.", "Success is earned.", "No shortcuts.",
        "Consistency beats talent.", "Results matter.", "Keep it simple.", "Work for it.", "Earn your rest.",
        "Stay in the zone.", "Keep the streak.", "Don't break the chain.", "Build the life you want.", "Success follows action.",
        "Be a closer.", "Make things happen.", "Take the lead.", "Be the example.", "Inspire yourself.",
        "Find a way.", "No limits.", "Growth mindset.", "Be phenomenal.", "Stay driven.",
        "Execute your vision.", "Progress over perfection.", "Daily discipline.", "Habits define you.", "Win the day.",
        "Stay resilient.", "Overcome obstacles.", "Be the boss.", "Take control.", "Your time is now.",
        "Make it happen.", "Whatever it takes.", "Be exceptional.", "Stay elite.", "Strive for more.",
        "Unlock your potential.", "Be a warrior.", "Stay powerful.", "Keep your head up.", "Eyes on the prize.",
        "Be courageous.", "Take the leap.", "Bet on yourself.", "Be original.", "Stay unique.",
        "Do it with passion.", "Passion fuels success.", "Be relentless.", "Stay aggressive.", "Attack the day.",
        "Be proactive.", "Lead the way.", "Stay ahead.", "Master your craft.", "Be a pro.",
        "Show up every day.", "Effort never dies.", "Be a game changer.", "Stay hungry for more.", "Keep climbing.",
        "Reach for the stars.", "Be a visionary.", "Stay creative.", "Innovation is key.", "Be a problem solver.",
        "Stay calm and execute.", "Patience and persistence.", "Be a legend.", "Live with purpose.", "Find your why.",
        "Be a leader.", "Stay humble.", "Work in silence.", "Let success talk.", "Be a doer.",
        "Get it done.", "Mission first.", "Stay tactical.", "Be strategic.", "Plan and execute.",
        "Focus on the mission.", "Be a finisher.", "Stay solid.", "Be reliable.", "Do it right.",
        "Quality over quantity.", "Be efficient.", "Stay fast.", "Speed is power.", "Be dynamic.",
        "Stay flexible.", "Adapt and overcome.", "Be versatile.", "Stay strong.", "Mental toughness.",
        "Be a winner.", "Champions train daily.", "Stay in the fight.", "Be the goat.", "Stay iconic.",
        "Make history.", "Be a pioneer.", "Stay bold.", "Be brave.", "Confidence is key.",
        "Be a master.", "Stay an expert.", "Keep learning.", "Knowledge is power.", "Be wise.",
        "Stay smart.", "Think ahead.", "Be sharp.", "Stay alert.", "Be mindful.",
        "Stay present.", "Focus on the task.", "Be diligent.", "Stay thorough.", "Attention to detail.",
        "Be precise.", "Stay accurate.", "Consistency is gold.", "Be a machine.", "Stay automatic.",
        "Build the habit.", "Routine is freedom.", "Be free.", "Stay independent.", "Be self-reliant.",
        "Stay strong-willed.", "Be determined.", "Grind now, shine later.", "Stay shining.", "Be a star.",
        "Light the way.", "Be the spark.", "Stay on fire.", "Be a flame.", "Burn bright.",
        "Stay hot.", "Keep the heat.", "Be a powerhouse.", "Stay energetic.", "Be vibrant.",
        "Stay lively.", "Be active.", "Stay busy.", "Be productive.", "Stay effective.",
        "Be a force.", "Stay impactful.", "Be significant.", "Stay meaningful.", "Purpose driven.",
        "Stay focused on goals.", "Be goal oriented.", "Stay ambitious.", "Be a dreamer.", "Stay a doer.",
        "Make an impact.", "Leave a legacy.", "Stay legendary.", "Be timeless.", "Stay classic.",
        "Be a hero.", "Save the day.", "Stay heroic.", "Be a champion.", "Stay victorious.",
        "Be a conqueror.", "Stay triumphant.", "Be a success.", "Stay successful.", "Keep winning.",
        "Be a achiever.", "Stay accomplished.", "Be fulfilled.", "Stay happy.", "Positive vibes only.",
        "Stay joyful.", "Be cheerful.", "Stay bright.", "Be optimistic.", "Focus on the good.",
        "Stay grateful.", "Be thankful.", "Stay blessed.", "Be a blessing.", "Give back.",
        "Stay kind.", "Be helpful.", "Stay supportive.", "Be a friend.", "Stay loyal.",
        "Be honest.", "Stay true.", "Integrity is key.", "Be ethical.", "Stay moral.",
        "Be decent.", "Stay upright.", "Be a good person.", "Stay great.", "Be wonderful.",
        "Stay amazing.", "Be fantastic.", "Stay superb.", "Be excellent.", "Strive for excellence.",
        "Be a perfectionist.", "Stay flawless.", "Be pure.", "Stay clean.", "Be neat.",
        "Stay organized.", "Be orderly.", "Stay disciplined.", "Be a soldier.", "Stay ready.",
        "Be prepared.", "Stay vigilant.", "Be on guard.", "Stay protective.", "Be a guardian.",
        "Stay a warrior.", "Be a fighter.", "Stay in control.", "Be the captain.", "Stay in command.",
        "Be the pilot.", "Stay on course.", "Be steady.", "Stay stable.", "Be firm.",
        "Stay grounded.", "Be humble.", "Stay low key.", "Be private.", "Stay mysterious.",
        "Be cool.", "Stay calm.", "Be collected.", "Stay composed.", "Be serene.",
        "Stay peaceful.", "Be quiet.", "Stay silent.", "Be still.", "Focus on breathing.",
        "Stay relaxed.", "Be at ease.", "Stay comfortable.", "Be content.", "Stay satisfied.",
        "Be whole.", "Stay complete.", "Be yourself.", "Stay unique.", "Be a original.",
        "Stay authentic.", "Be real.", "Stay genuine.", "Be sincere.", "Stay honest.",
        "Be transparent.", "Stay open.", "Be curious.", "Stay inquisitive.", "Keep asking.",
        "Keep searching.", "Stay a seeker.", "Find the truth.", "Stay wise.", "Be a philosopher.",
        "Stay a thinker.", "Be a creator.", "Stay an artist.", "Make art.", "Be beautiful.",
        "Stay elegant.", "Be graceful.", "Stay classy.", "Be sophisticated.", "Stay refined.",
        "Be polished.", "Stay professional.", "Be a pro.", "Stay a master.", "Be a god.",
        "Stay divine.", "Be holy.", "Stay sacred.", "Be eternal.", "Stay infinite.",
        "Be the universe.", "Stay connected.", "Be one.", "Stay whole.", "The end is the beginning."
    )
}
